apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: gallety-app-pv-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: galley-app-deployment
  labels:
    app: gallery-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery-app
  template:
    metadata:
      labels:
        app: gallery-app
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: gallery-app-pv-claim
      containers:
        - name: gallery-app
          image: ahmedjabareen/gallery-app:lattest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/data"
              name: pv-storage

---

apiVersion: v1
kind: Service

metadata:
  name: gallery-app

spec:
  selector:
    app: gallery-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP